Header
MacRoberto/travel-segundo-parcial pull request #17
Opened 2024-10-29 06:15 UTC by Fernando7Josue

Se realizo el header, con este ultimo se termino la parte principal del proyecto se realizo

2024-10-29 06:55 UTC, JJS74 commented on travel.html
>      </header>
falta un espacio en esta parte

2024-10-29 07:00 UTC, JJS74 requested changes
Todo se ve correcto y en forma, solo haría falta cambiar unas cuantas cosas, pero por todo lo demas con respecto al codigo se ve muy bien

2024-10-29 07:00 UTC, JJS74 commented on css/travel.css
siento que al final haria falta un espacio si no me equivoco

2024-10-29 07:00 UTC, JJS74 commented on travel.html
Aqui tambien al final haria falta un espacio al final

2024-10-29 17:34 UTC, LuisAmir04 requested changes
El codigo nuevo me parece bien pero aparece como si no hubiera una linea en blanco al final de travel.css y travel.html, si no es asi comentalo. 
travels.css:
![Screenshot_59](https://github.com/user-attachments/assets/c723b5e0-1e7d-4c38-91b1-36da2204b87b)
travel.html:
![Screenshot_60](https://github.com/user-attachments/assets/8c51c68f-17c1-4056-bf1b-430b6a17e836)

2024-10-30 03:42 UTC, MacRoberto commented on travel.html
> -        <img src="" alt="">
Pienso que este codigo esta de más. Favor de revisarlo.

2024-10-30 03:43 UTC, MacRoberto commented on travel.html
> -                <img src="" alt="">
Pienso que no tiene caso poner este código.

2024-10-30 03:44 UTC, MacRoberto commented on travel.html
> -                <img src="" alt="">
Pienso que no tiene sentido poner este código.

2024-10-30 04:24 UTC, MacRoberto approved these changes
He revisado el trabajo minuciosamente y esta todo bien

2024-10-30 04:24 UTC, merged