Our service
MacRoberto/travel-segundo-parcial pull request #19
Opened 2024-11-03 01:05 UTC by JJS74

![image](https://github.com/user-attachments/assets/6a45b4b9-b5ae-4610-ba90-a1482a24634a)

Se hicieron modificaciones visuales y se añadio un poco del issue Our service

2024-11-03 19:52 UTC, LuisAmir04 commented on css/travel.css
> +}
El simbolo rojo debajo del corchete (linea 156) indica que hace falta agregar una linea en blanco adiccional al codigo

2024-11-03 19:56 UTC, LuisAmir04 requested changes
Por el momento me parece bien para mi pero habria que añadir una linea en blanco en el Travel.css despues de la linea 156

2024-11-04 18:24 UTC, JJS74 commented
- [ ] Se realizaron cambios minimos en el codigo con respecto a las peticiones

2024-11-04 19:10 UTC, Fernando7Josue commented
LGTM

2024-11-04 19:11 UTC, Fernando7Josue approved these changes
LGTM

2024-11-04 19:36 UTC, LuisAmir04 approved these changes
LGTM

2024-11-04 20:05 UTC, Emiliano-dev25052 commented
LGTM

2024-11-04 20:06 UTC, Emiliano-dev25052 approved these changes

2024-11-05 09:35 UTC, MacRoberto commented on travel.html
> +                    <div class="Text-o">
Este contenedor ( div class="Texto-o" )no tiene las mismas dimensiones que el contenedor de la línea 70 y 86, los cuales son de la misma clase, esto esta causando la desalineación entre el logo de ticket booking y el texto.
Favor de corregirlo.
![corrección 1](https://github.com/user-attachments/assets/39cb7b2d-1daf-4dc0-bb7c-f74829eb3ebe)

2024-11-07 02:21 UTC, MacRoberto approved these changes
![image](https://github.com/user-attachments/assets/f1804da3-8ee2-4ce0-8b02-66bbcf21da1b)
Estoy viendo que se hicieron los ajustes necesarios solicitados.

2024-11-07 02:28 UTC, merged